name: test

on:
    push:
        branches:
        -   main
    pull_request:
        branches:
        -   '*'

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

# Force to use color
env:
    FORCE_COLOR: true

jobs:
    test_and_coverage:
        name: 'Test with ${{ matrix.py }} on ${{ matrix.os }}: numpy==${{ matrix.numpy }} scipy==${{ matrix.scipy }} pandas==${{ matrix.pandas }}'
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                py: ['3.11', '3.12']
                os: [macos-13, macos-14]
                numpy: [1.25, 1.26]
                scipy: [1.12, 1.13]
                pandas: [2.1, 2.2]
        steps:
        -   uses: actions/checkout@v4
        -   name: Setup python
            uses: actions/setup-python@v5
            with:
                python-version: ${{ matrix.py }}
        -   name: Install
            run: |
                python -m pip install -r requirements.txt
                # for 3.12
                pip install setuptools
        -   name: Try different versions
            run: python -m pip install numpy==${{ matrix.numpy }} scipy==${{ matrix.scipy }} pandas==${{ matrix.pandas }}
        -   name: Run tests
            run: python -m pytest test_temp.py -vv
